In [1]:
import numpy as np

# 创建一维数组

In [2]:
arr1 = np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

# 创建二维数组

In [3]:
arr2 = np.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

# 打印数组维度、形状、元素数量、元素类型

In [4]:
print(arr1.ndim)
print(arr2.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr1.size)
print(arr2.size)
print(arr1.dtype)
print(arr2.dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


# 创建包含6个元素全为0的一维数组

In [5]:
arr_all_0 = np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

# 创建包含6个元素全为1的一维数组

In [6]:
arr_all_1 = np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

# 创建一维数组，元素为10到20间的偶数

In [7]:
arr_even = np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])