In [1]:
import numpy as np

In [3]:
arr1 = np.array([1,3,2,4,9])
arr2 = np.ones(5)
arr3 = np.zeros(3)
print(arr1)
print(arr2)
print(arr3)

[1 3 2 4 9]
[1. 1. 1. 1. 1.]
[0. 0. 0.]


# 连接数组

In [4]:
arr4 = np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

# 更改数组，对其排序

In [5]:
arr1.sort()
arr1

array([1, 2, 3, 4, 9])

# 根据索引打印数组元素

In [6]:
print(arr1[2])
print(arr1[-3])

3
3


# 数组切片

In [7]:
arr1[1:4]

array([2, 3, 4])

# 数组相加

In [8]:
arr1 + arr2

array([ 2.,  3.,  4.,  5., 10.])

# 数组运算

In [9]:
arr1 * -5

array([ -5, -10, -15, -20, -45])

# 打印数组最大值、最小值、和、平均值

In [10]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


# 对数组进行逻辑操作

In [11]:
arr1[(arr1<1)|(arr1>3)]

array([4, 9])